### PR TITLE
Improve the app tutorial

### PR DESCRIPTION
**Pull request by dira**
- super dense content, hard to keep track of where you are -> massively spaced out
- mvc + erb + dynamic info in one go was hard to digest ->  moved the Pages controller first (+ explanations for routes, controller, views - html only) and the full scaffold comes after (the dynamic part:  models, erb)
- link to a real-time HTML playground

This is the result of experimentation and improvements from the team of coaches of RailsGirls Bucharest. We used it and it worked really well.

You can see it at http://railsgirls-bucharest.herokuapp.com/app-bucharest/.

### CODE REVIEW

**Comment by Saichethan** [comment]
Interactive GIF's , video links and digital playground helps

**Comment by FloorD** [comment]
have you been keeping http://railsgirls-bucharest.herokuapp.com/app-bucharest/ up to date with new Ruby/Rails and gem versions?

**Comment by hanislong** [comment]
Good

**Comment by coolbrg** [comment]
It seems to have been outdated.

**Comment by dira** [comment]
closing (outdated)

**Pull request closed without merging**
