### PR TITLE
guides: update install guide for Ruby 3 (Win/Mac)

### PR DESCRIPTION
**Pull request by mble**
As Ruby 2.7 is end-of-life 2023-03-31 (https://endoflife.date/ruby), we need to update the guide for Ruby 3. This commit does this for Windows and Mac, and handles the default shell change in newer versions of MacOS.

As of Ruby 3, webrick is not available without a separate gem (ref: https://www.ruby-lang.org/en/news/2020/12/25/ruby-3-0-0-released/) so to allow the jekyll run, we need to add it to the Gemfile.

ChromeOS, Linux and cloud setup are not changed - this will be a follow up PR.

### CODE REVIEW

**Comment by ivantoniev** [comment]
Just a small comment for the description, it's 2.6 that's eol in march 2022 and 2.7 in march 2023 🙂

**Comment by leesheppard** [comment]
@mble Your PR contains a commit to add Webrick into the gemfile. Is there a reason for this? it is out of scope for the PR you have raised on editing the guides markdown.

**Comment by mble** [comment]
@leesheppard I'll make this clearer in the PR, apologies. As of Ruby 3, `webrick` is not available without a separate gem (ref: https://www.ruby-lang.org/en/news/2020/12/25/ruby-3-0-0-released/) so to allow the `jekyll` run, we need to add it to the Gemfile.

**Review by tombruijn — APPROVED** [review]
I want to go ahead and merge this, or cherry-pick the changes. It has a couple changes like macOS ZSH, VS code in favor of Atom (now that it's no longer maintained) and such that are good additions.

I can confirm that webrick as a gem is needed for Ruby 3, but this PR was mostly focused on the guides using Ruby, not upgrading the Jekyl app itself to Ruby 3. I can't see what version it's supposed to be using actually.

For future PRs, I would recommend leaving out the changes in Markdown formatting. It makes it difficult to find the actual changes you're making and review them.

**Comment by leesheppard** [comment]
Can we amend this PR to include the latest releases of Ruby 3.0.5 or 3.2.0 ?

**Comment by tombruijn** [comment]
Ruby 3.2 has just been released, some gems might still have some issues. Ruby 3.1 would be a good compromise. We can update to that right after merging this PR.

**Pull request merged**
