### PR TITLE
Rails girls athens 2017 fixes

### PR DESCRIPTION
**Pull request by agorf**

### CODE REVIEW

**Comment by hsbt** [comment]
@agorf This pull requests contains style fixes without athens event? Is this intentional changes?

**Comment by agorf** [comment]
If with "style fixes" you mean changing `<br />` to `<br>` and `<b>` to `<strong>` then, yes, they are intentional. Since Rails uses an HTML5 doctype, these tags are invalid and should not be included in the guides.

**Comment by agorf** [comment]
@hsbt Now that I think of it, you have a point about `<b>` - it may break some styles since I haven't updated the relevant CSS. I can remove this commit from the PR if you want (and leave the `<br />` to `<br>`).

**Comment by hsbt** [comment]
@agorf Make sense. I'm ok to merge your change. Can I merge this change now?

**Comment by agorf** [comment]
@hsbt Yeap, go ahead. I've removed the commit that changed `<b>` to `<strong>` to avoid breaking any CSS styles.

**Comment by agorf** [comment]
@hsbt Ping?

**Comment by hsbt** [comment]
@agorf Thanks a lot :octocat:

**Comment by agorf** [comment]
@hsbt Glad to help!

**Pull request merged**
